Tensors are a type of data structure used in linear algebra, and like vectors and
matrices, you can calculate arithmetic operations with tensors.

#### What are Tensors ?
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.
In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.

In [1]:
# create tensor
from numpy import array
T = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]
])
print(T.shape)

(3, 3, 3)


In [8]:
from numpy import tensordot

A = array([1,2])
B = array([3,4])
C = tensordot(A, B, axes=0)
D = tensordot(A, B, axes=1)
print(C)
print(D)

[[3 4]
 [6 8]]
11


In [14]:
from numpy.linalg import qr
from numpy.linalg import cholesky
from scipy.linalg import lu

A = array([
    [1,2,3],
    [3,4,5],
    [5,6,7]
])

P,L,U = lu(A)
Q,R = qr(A)

print(Q)
print(R)


[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[ -5.91607978e+00  -7.43735744e+00  -8.95863510e+00]
 [  0.00000000e+00   8.28078671e-01   1.65615734e+00]
 [  0.00000000e+00   0.00000000e+00  -6.66133815e-16]]


### Eigen Decomposition
<pre>
Decomposes a matrix into Eigen values and Eigen Vectors
play a imp role in the PCA.
</pre>

### A vector is an eigenvector of a matrix if it satisfies the equation : $A \cdot \upsilon = \lambda \cdot \upsilon$
#### $ A = Q \cdot \Lambda \cdot Q^{-1}$
- $Q$ is a matrix comprised of the eigenvectors
- $\Lambda$  is the diagonal matrix comprised of the eigenvalues
- $Q^{-1}$ is the inverse of the matrix comprised of the eigenvectors

In [3]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[  1.61168440e+01  -1.11684397e+00  -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [8]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 1])
print(B)
C = vectors[:, 1] * values[1]
print(C)

[ 0.87764976  0.09688771 -0.68387434]
[ 0.87764976  0.09688771 -0.68387434]


In [9]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


## Singular Value Decomposition
it is often used in a wide array of applications including compressing, denoising, and data reduction

#### $A = U \cdot \Sigma \cdot V^{T}$
- $A$ is the real $n \times m$ matrix that we wish to decompose
- $U$ is an $m \times m$ matrix
- $\Sigma$ is an $m \times n$ diagonal matrix
- $V^{T}$ is the $V$ transpose of an $n \times n$ matrix

In [12]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[ 9.52551809  0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [19]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix

Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(Sigma)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[ 9.52551809  0.        ]
 [ 0.          0.51430058]
 [ 0.          0.        ]]
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
